#!/usr/bin/env node
/*
 * Bake the newest file in layouts/ into data/layout.js, so opening index.html
 * lands straight on your own layout instead of the factory default.
 *
 * The viewer runs from file:// and can't read the filesystem, so the layout has
 * to arrive as a script. Drag-and-drop still works and takes precedence (it is
 * remembered in localStorage); this is just a better starting point.
 *
 *   node tools/bake.js            # newest layouts/*.json|keymap
 *   node tools/bake.js PATH       # a specific file
 */
'use strict';

var fs = require('fs');
var path = require('path');

var ROOT = path.resolve(__dirname, '..');
var explicit = process.argv[2];

function newestLayout() {
  var dir = path.join(ROOT, 'layouts');
  var files = fs.readdirSync(dir)
    .filter(function (f) { return /\.(json|keymap|dtsi)$/i.test(f); })
    .map(function (f) {
      var p = path.join(dir, f);
      return { p: p, mtime: fs.statSync(p).mtimeMs };
    })
    .sort(function (a, b) { return b.mtime - a.mtime; });
  if (!files.length) {
    console.error('Nothing to bake — put a .json or .keymap in layouts/ first.');
    process.exit(1);
  }
  return files[0].p;
}

var src = explicit ? path.resolve(explicit) : newestLayout();
var text = fs.readFileSync(src, 'utf8');
var name = path.basename(src);

var out = path.join(ROOT, 'data/layout.js');
fs.writeFileSync(out,
  '/* GENERATED by tools/bake.js — do not edit. Source: ' + name.replace(/\*\//g, '') + ' */\n' +
  '(function (root) {\n' +
  '  root.G80_LAYOUT_NAME = ' + JSON.stringify(name) + ';\n' +
  '  root.G80_LAYOUT_SOURCE = ' + JSON.stringify(text) + ';\n' +
  '})(typeof self !== \'undefined\' ? self : this);\n');

console.log('baked ' + path.relative(ROOT, src) + ' -> data/layout.js (' +
  fs.statSync(out).size + ' bytes)');
console.log('open index.html — clear the viewer\'s saved layout with "Default" if it shows something else.');
