#!/usr/bin/env node
/*
 * Put the canonical keymap where the firmware build reads it:
 *
 *   layouts/go60.keymap (newest .keymap)  ->  firmware/config/go60.keymap
 *
 * The copy is gitignored and regenerated by CI on every build, so it can't
 * drift from the canonical file. This also validates the keymap (Go60, 60
 * bindings per layer, behaviours resolve) and refuses to place one that
 * doesn't parse — a build should fail here, not compile something wrong.
 *
 * The JSON staleness guard below is a relic of the my.moergo.com era kept as
 * a tripwire: layouts/ holds no .json any more, but if one ever reappears
 * newer than the keymap, that's a sign someone went back to editing the old
 * format and the keymap silently lags it.
 */
'use strict';

var fs = require('fs');
var path = require('path');

var ROOT = path.resolve(__dirname, '..');
var Parse = require(path.join(ROOT, 'js/parse.js'));

function fail(msg) { console.error('ABORT: ' + msg); process.exit(1); }

function newest(dir, re) {
  var files = fs.readdirSync(dir)
    .filter(function (f) { return re.test(f); })
    .map(function (f) {
      var p = path.join(dir, f);
      return { p: p, name: f, mtime: fs.statSync(p).mtimeMs };
    })
    .sort(function (a, b) { return b.mtime - a.mtime; });
  return files[0] || null;
}

var dir = path.join(ROOT, 'layouts');
var keymap = newest(dir, /\.keymap$/i);
var json = newest(dir, /\.json$/i);
var force = process.argv.indexOf('--force') >= 0;

if (!keymap) fail('no .keymap in layouts/ — export one from my.moergo.com/go60.');

if (json && json.mtime > keymap.mtime && !force) {
  fail('a layout .json is newer than the keymap.\n' +
    '  newest .json:   ' + json.name + '\n' +
    '  newest .keymap: ' + keymap.name + '  (older)\n' +
    'The keymap is the source of truth now — apply the change to it directly\n' +
    'and delete the JSON, or pass --force if the JSON is just an artifact.');
}

var text = fs.readFileSync(keymap.p, 'utf8');
var model = Parse.parseAuto(text, { title: keymap.name });
if (model.error) fail('keymap does not parse: ' + model.error);
if (model.ok === false) {
  console.error('ABORT: keymap fails validation:');
  (model.errors || []).forEach(function (e) { console.error('  ' + e); });
  process.exit(1);
}

var out = path.join(ROOT, 'firmware', 'config', 'go60.keymap');
fs.writeFileSync(out, text);
console.log('synced ' + keymap.name + ' -> firmware/config/go60.keymap');
console.log('  ' + model.layers.length + ' layers, ' + (model.combos || []).length +
  ' combos, validates clean');
console.log('\ncommit + push to build, then: tools/flash.sh');
